<?php
/**
 * Created by PhpStorm.
 * User: gok11139
 * Date: 2017/7/24
 * Time: 10:44
 */

namespace app\modules\author\controllers;

use Yii;
use yii\web\controller;

class CController extends controller
{
//    public $layout = 'main';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionLogin(){

    }
}