<?php
/**
 * Created by PhpStorm.
 * User: gok11139
 * Date: 2017/7/24
 * Time: 10:44
 */

namespace app\modules\manager\controllers;

use Yii;
use yii\web\controller;

class CController extends controller
{
    public $layout = 'fixed';
    public function init()
    {
//        $this->layout = 'left_nav';
        parent::init(); // TODO: Change the autogenerated stub
    }
}